### ISSUE TITLE
how to have multi route 

### ISSUE THREAD

**Issue by vahidalvandi** [eliseekn/laravel-react-starter-kit#2]
please show how i can multi react route ? and how it with sanctum, i saw todo sample. 
i need multi route and code spliting , auth 

 thanks

**Comment by eliseekn** [comment]
Hello, thanks for using my starter kit. For the routing management, you can use [React Router](https://reactrouter.com/en/main/start/overview).

What do you mean by code splitting ? Even if it's a monolithic application, each part use its own architecture.
